CREATE TABLE "app_menu_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "app_menu_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "app_menu_menu_page" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_menu_menu_page_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"menu_id" integer NOT NULL,
	"page_number" integer NOT NULL,
	"image_url" varchar(1024) NOT NULL,
	"annotations" json DEFAULT '[]'::json NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_menu_menu" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_menu_menu_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "app_menu_menu_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "app_menu_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_menu_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"mp_payment_id" varchar(255),
	"mp_subscription_id" varchar(255),
	"amount" integer,
	"currency" varchar(10) DEFAULT 'ARS',
	"status" varchar(50) NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_menu_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_menu_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(255),
	"email_verified" timestamp with time zone,
	"image" varchar(255),
	"business_name" varchar(255),
	"business_slug" varchar(100),
	"subscription_status" varchar(50) DEFAULT 'trial' NOT NULL,
	"subscription_expiry" timestamp with time zone,
	"mp_customer_id" varchar(255),
	CONSTRAINT "app_menu_user_email_unique" UNIQUE("email"),
	CONSTRAINT "app_menu_user_business_slug_unique" UNIQUE("business_slug")
);
--> statement-breakpoint
CREATE TABLE "app_menu_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "app_menu_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "app_menu_account" ADD CONSTRAINT "app_menu_account_user_id_app_menu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_menu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_menu_menu_page" ADD CONSTRAINT "app_menu_menu_page_menu_id_app_menu_menu_id_fk" FOREIGN KEY ("menu_id") REFERENCES "public"."app_menu_menu"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_menu_menu" ADD CONSTRAINT "app_menu_menu_user_id_app_menu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_menu_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_menu_payment" ADD CONSTRAINT "app_menu_payment_user_id_app_menu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_menu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_menu_session" ADD CONSTRAINT "app_menu_session_user_id_app_menu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_menu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "app_menu_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "page_menu_id_idx" ON "app_menu_menu_page" USING btree ("menu_id");--> statement-breakpoint
CREATE INDEX "menu_user_id_idx" ON "app_menu_menu" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "menu_slug_idx" ON "app_menu_menu" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "payment_user_id_idx" ON "app_menu_payment" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "app_menu_session" USING btree ("user_id");